In [1]:
import requests
import pandas as pd
from requests_ntlm import HttpNtlmAuth
import plotly.express as px
from datetime import date

In [2]:
today = date.today().strftime('%Y-%m-%d')
url = 'https://opendata.ecdc.europa.eu/covid19/casedistribution/csv'
filename = today + '.csv'
filepath = 'data/' + filename

In [3]:
r = requests.get(url, auth=HttpNtlmAuth(':',':'))

In [4]:
with open(filepath, 'wb') as file:
    file.write(r.content)

In [6]:
data = pd.read_csv(filepath, encoding='cp1252')
data

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018
0,28/03/2020,28,3,2020,16,1,Afghanistan,AF,AFG,37172386.0
1,27/03/2020,27,3,2020,0,0,Afghanistan,AF,AFG,37172386.0
2,26/03/2020,26,3,2020,33,0,Afghanistan,AF,AFG,37172386.0
3,25/03/2020,25,3,2020,2,0,Afghanistan,AF,AFG,37172386.0
4,24/03/2020,24,3,2020,6,1,Afghanistan,AF,AFG,37172386.0
...,...,...,...,...,...,...,...,...,...,...
7315,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
7316,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0
7317,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0
7318,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0
7319,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0